MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
Metrics/LineLength:
  Max: 120
Style/AsciiComments:
  Enabled: no
Style/Documentation:
  Enabled: no

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
