language: ruby
rvm:
  - 2.2.6
bundler_args: --without production
services:
  - postgresql
  - redis-server
addons:
  postgresql: "9.3"
before_script:
  - bundle exec sidekiq -q default -q mailers -q cron -d
  - psql -c 'create database cforum_test;' -U postgres
