dist: trusty
sudo: required
language: ruby
bundler_args: --without production
services:
  - postgresql
  - redis-server
addons:
  postgresql: "9.6"
  chrome: stable
before_script:
  - bundle exec sidekiq -q default -q mailers -q cron -d -L /tmp/sidekiq.log
  - psql -c 'create database cforum_test;' -U postgres
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
